### ISSUE TITLE
mmaparrays=true , ERROR: could not create file mapping:

### ISSUE THREAD

**Issue by paulanalyst** [timholy/HDF5.jl#215] opened 2015-02-02 09:39 UTC
_       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+2847 (2015-01-21 18:34 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit fc61385 (11 days old master)
|__/                   |  x86_64-w64-mingw32

julia> y=rand(100,100);

julia> using HDF5,JLD

julia> save("mydata.jld","y",y)

julia> file = jldopen("mydata.jld", "r", mmaparrays=true)
Julia data file version 0.1.0: mydata.jld

julia> y = read(file, "y")
ERROR: could not create file mapping: Access is denied.
 in error at error.jl:19 (repeats 2 times)

On julia 3.3.0 is the same.
Paul

**Comment by paulanalyst** [comment] 2015-02-02 10:59
And at HDF5 the same storry:
               _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: http://docs.julialang.org
   _ _   _| |_  __ _   |  Type "help()" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.4.0-dev+2847 (2015-01-21 18:34 UTC)
 _/ |\__'_|_|_|\__'_|  |  Commit fc61385 (11 days old master)
|__/                   |  x86_64-w64-mingw32

julia> using HDF5

julia> fid = h5open("labels_F.h5")
HDF5 data file: labels_F.h5

julia> names(fid)
1-element Array{Union(ASCIIString,UTF8String),1}:
 "mygroup"

julia> dump(fid)
HDF5.HDF5File len 1
  mygroup: HDF5.HDF5Group len 2
    A: HDF5Dataset (2,) : [0.6746392026277483,0.7684441952692127
    F: HDF5Dataset (5932868,193) : [3.5542404799487705e-5,-3.858688683079578e-6,-9.791484268731103e-5,-7.379889331
559129e-5,-2.6457069809417572e-5

julia> g = fid["mygroup"]
HDF5 group: /mygroup (file: labels_F.h5)

julia> dset = g["F"]
HDF5 dataset: /mygroup/F (file: labels_F.h5)

julia> ismmappable(dset)
true

julia> readmmap(dset)
ERROR: could not create file mapping: Access is denied
 in error at error.jl:19 (repeats 2 times)

**Comment by timholy** [comment] 2015-02-02 11:48
Works for me on Linux. If you have a Linux machine, can you try it there?

**Comment by paulanalyst** [comment] 2015-02-03 10:15
Ok, on ubuntu is workin.
What on win? my win:  7/64 I am loged as admin (lik is posible;) )
Paul

**Comment by timholy** [comment] 2015-02-03 10:47
Can't help you, unfortunately. CCing @tkelman to see if he knows.

**Comment by tkelman** [comment] 2015-02-03 19:39
This is #89. HDF5.jl with mmap is broken on Windows. I don't know of a fix. If similar mmap functionality works in C or Python bindings to HDF5, we could look into what they're doing differently.

**Comment by timholy** [comment] 2015-02-03 23:13
Closing as a dupe of #89.

**Closed by timholy** 2015-02-03 23:13 UTC

**Comment by paulanalyst** [comment] 2015-02-04 08:29
Is posible soon ?
P

W dniu 2015-02-03 o 20:39, Tony Kelman pisze:

**Comment by timholy** [comment] 2015-02-04 10:36
Since no one seems to understand why it fails, there's no plan in place for fixing it.

**Comment by paulanalyst** [comment] 2015-02-04 10:41
I see:/
Tim, is the same fast to read data by h5open and to read[:,1]( read 
range) of dataset like by readmmap?
P.
W dniu 2015-02-04 o 11:36, Tim Holy pisze:
> Since no one seems to understand why it fails, there's no plan in 
> place for fixing it.

**Comment by timholy** [comment] 2015-02-04 11:48
No idea. Perhaps test it yourself (on Linux, where both work), and let us know what you find.
